portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('projet/<int:id>-<slug:slug>', views.more, name='more')
]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models
from django.utils import timezone

# Project model
class Project(models.Model):
    name = models.CharField(max_length=100, verbose_name="Project title")
    slug = models.SlugField(max_length=100, null=True)
    image = models.ImageField(upload_to='gallery', null=True, verbose_name="Project\'s Image")
    labels = models.CharField(max_length=100, null=True, verbose_name="Languages used")
    desc = models.TextField(null=True, verbose_name="Project description")
    github = models.CharField(max_length=200, null=True, blank=True, verbose_name="GitHub URL")
    demo = models.CharField(max_length=200, null=True, blank=True, verbose_name="Demo URL")
    date = models.DateTimeField(default=timezone.now, verbose_name="Day of publication")
    
    class Meta:
        verbose_name = "Project"
        ordering = ['-date']
    
    def __str__(self):
        return self.name

# Upload file in Django Admin
class UploadImg(models.Model):
    projet = models.ForeignKey(Project, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True, verbose_name="Picture name")
    link = models.ImageField(upload_to='gallery', null=True, verbose_name="Picture")
    
    class Meta:
        verbose_name = "Picture"
        ordering = ['-name']

    def __str__(self):
        return self.name

# Contact model
class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name="Name")
    email = models.EmailField(max_length=100, verbose_name="Email")
    message = models.TextField(verbose_name="Message")
    date = models.DateTimeField(default=timezone.now, verbose_name="Day of publication")

    class Meta:
        verbose_name = "Contact"
        ordering = ['-date']

    def __str__(self):
        return self.name

portfolio/forms.py
from django import forms

# Contact Form (in the footer)
class ContactForm(forms.Form):
    contactName = forms.CharField(required=True)
    contactEmail = forms.EmailField(required=True)
    message = forms.CharField(required=True,widget=forms.Textarea)

portfolio/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from portfolio.models import Project, UploadImg
from portfolio.forms import ContactForm
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.contrib import messages

# Home page
def index(request):
    projects = Project.objects.all()
    formInit = contact(request)
    return render(request, 'index.html', {'last_projects' : projects, 'form' : formInit})

# Entire project
def more(request, id, slug):
    project = get_object_or_404(Project, id=id, slug=slug)
    fichiers = UploadImg.objects.filter(projet=project)
    formInit = contact(request)
    return render(request, 'layouts/project.html', {'project':project, 'fichiers':fichiers, 'form' : formInit})

# Contact form
def contact(request):
    formInit = ContactForm

    if request.method == 'POST':
        form = formInit(data=request.POST)
        if form.is_valid():
            contactName = request.POST.get('contactName', '')
            contactEmail = request.POST.get('contactEmail', '')
            message = request.POST.get('message', '')
            template = get_template('contactTemplate.txt')
            context = {'contactName': contactName,'contactEmail': contactEmail,'message': message,}
            content = template.render(context)
            email = EmailMessage("New message", content, "Portfolio Website" +'', "", headers = {'Reply-To': contactEmail })
            email.send()
            # Notification of success for the contact form
            messages.add_message(request, messages.SUCCESS, 'Your message has been sent successfully !')
            return redirect('index')
        messages.add_message(request, messages.ERROR, 'Your message could not be sent, please try again.')
        return redirect('index')

portfolio/templates/index.html
{% extends 'layouts/gabarit.html' %}
{% load static %}

    {% block content %}
    <!-- Projects -->
    <div class="in scene_element scene_element--fadeinup">
        <h2 id="blog">My projects</h2>

        <ul id="blog">
            {% for project in last_projects %}
                <a class="animsition-link" href="{% url 'more' id=project.id slug=project.slug %}" data-animsition-out-class="overlay-slide-out-right"><li style="background-image:url('{{ project.image.url }}');"><h2>{{ project.name }}</h2><p>{{ project.desc|truncatewords_html:9 }}</p><p class='more'>En lire plus..</p></li></a>
            {% empty %}
            <p>No project.</p>
            {% endfor %}
        </ul>

        <!-- Skills -->
        <h2 id="competences" class="darktheme">My skills</h2>
        <div id="skills">
            <i class="devicon-html5-plain colored" data-title="HTML5"></i>
            <i class="devicon-css3-plain colored" data-title="CSS3"></i>
            <i class="devicon-javascript-plain colored" data-title="Javascript"></i>
            <i class="devicon-php-plain colored" data-title="PHP"></i>
            <i class="devicon-postgresql-plain-wordmark colored" data-title="PostgreSQL"></i>
            <i class="devicon-python-plain-wordmark colored" data-title="Python"></i>
            <i class="devicon-bootstrap-plain colored" data-title="Bootstrap"></i>
            <i class="devicon-wordpress-plain colored" data-title="WordPress"></i>
            <i class="devicon-django-plain colored" data-title="Django"></i>
        </div>
        
    </div>
    {% endblock %}

portfolio/templates/layouts/footer.html
    {%load static %}
    <!-- Footer -->
    <footer>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none">
            <polygon fill="white" points="100,0 0,100 0,0"></polygon>
        </svg>

        <div class="in">
            <div id="contact">
                <h2>Contact me</h2>
                <form role="form" method="post" action="">
                    {% csrf_token %}
                    <input type="text" name="contactName" required id="id_contactName" placeholder="Name">
                    <input type="email" name="contactEmail" required id="id_contactEmail" placeholder="E-mail">
                    <textarea name="message" required id="id_message" placeholder="Your message.." maxlength="250"></textarea>
                    <input type="submit" value="Send">
                </form>
            </div>
            <p>&copy; Sotramp 2020 - All rights reserved</p>
            <a href="#menu"><p><i class="fas fa-chevron-up"></i> Go up</p></a>
        </div>
    </footer>
    <!-- animation-->
    </div>

    <!-- javascript -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mobile.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mobile.custom.min.js' %}"></script>
    <!-- animsition.js -->
    <script src="{% static 'js/animsition.min.js'%}"></script>
    <script>
        $(document).ready(function() {
          $('.animsition-overlay').animsition({
            inClass: 'overlay-slide-in-bottom',
            outClass: 'overlay-slide-out-top',
            overlay : true,
            overlayClass : 'animsition-overlay-slide',
            overlayParentElement : 'body'
          })
          .one('animsition.inStart',function(){
      
            $('body').removeClass('bg-init');
      
            console.log('event -> debut');
          })
          .one('animsition.inEnd',function(){
      
            console.log('event -> fin');
          });
        });
    </script>
</body>
</html>

portfolio/templates/layouts/gabarit.html
{% load static %}

<!-- SOTRAMP 2020 -->
<!DOCTYPE html>
<html>
<head>  
    <meta charset="UTF-8">
    <title>Sotramp - {% block title %}Portfolio{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/lightbox.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/animsition.min.css'%}" rel="stylesheet"  type="text/css">
    <link href="{% static 'css/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <style media="screen">
        .bg-init,
        .animsition-overlay-slide {
          background-color: #f5cd79;
        }
    </style>
</head>
 <body class="bg-init">
    <div class="animsition-overlay">
    <!-- Lightbox background -->
    <div class="voile"></div>

    <!-- Notification of success for the contact form  -->
    {% if messages %}
    {% for message in messages %}
        <div id="notif{{ message.tags }}" class="notif">{{ message }} <i id="closeNotif" class="fas fa-times"></i></div>
    {% endfor %}
    {% endif %}

    <!-- Main menu -->
    <header class="darktheme">
        <ul id="menu" class="darktheme">
            <a class="animsition-link" href=".." data-animsition-out-class="overlay-slide-out-left"><li>Home</li></a>
            <a href="#blog"><li>Projects</li></a>
            <a class="js-scrollTo" href="#competences"><li>Skills</li></a>
            <a href="#contact"><li>Contact</li></a>
            <a href="#"><li>CV</li></a>
        </ul>

        <div id="content">

            <!-- Logo -->
            <h1>Sotramp</h1>
            <div id="social">
                <a href="https://twitter.com/sotramp" target="_blank"><i class="fab fa-twitter fa-2x"></i></a>
                <a href="https://www.instagram.com/damienclairet/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
            </div>

            <!-- Right paragraph -->
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea aspernatur, impedit harum, tempore perspiciatis vitae culpa cum suscipit possimus aliquid obcaecati a magnam officiis labore. Ab ipsa delectus tenetur nesciunt.</p>
        </div>

    <!-- Diagonal -->
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none">
        <polygon fill="white" points="0,100 100,0 100,100"/>
    </svg>
    </header>

    {% block content %}{% endblock %}

{% include 'layouts/footer.html' %}

portfolio/templates/layouts/header.html
{% load static %}

<!-- SOTRAMP 26/12 -->
<!DOCTYPE html>
<html>
<head>  
    <meta charset="UTF-8">
    <title>Sotramp - Portfolio</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/scroll.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/smoothstate.js' %}"></script>
</head>
</html>
<body>

    <!-- Main menu -->
    <header>
        <ul id="menu">
            <a href="../"><li>Accueil</li></a>
            <a href="#blog"><li>Projets</li></a>
            <a href="#competences"><li>Compétences</li></a>
            <a href="#contact"><li>Contact</li></a>
            <a href="#"><li>CV</li></a>
        </ul>

        <div id="content">

            <!-- Logo -->
            <h1>sotramp</h1>
            <div id="social">
                <a href="https://twitter.com/sotramp" target="_blank"><i class="fab fa-twitter fa-2x"></i></a>
                <a href="https://www.instagram.com/damienclairet/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
            </div>

            <!-- Right paragraph -->
            <p>Étudiant en 2ème année de DUT Informatique, je m'intéresse au développement web depuis maintenant plusieurs années. Blabla en faite c'est juste que je me fais chier du coup je fais un portfolio.</p>
        </div>

    <!-- Diagonal -->
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none">
        <polygon fill="white" points="0,100 100,0 100,100"/>
    </svg>
    </header>

portfolio/templates/layouts/project.html
{% extends 'layouts/gabarit.html' %}
{% block title %}{{ project.name }}{% endblock %}
{% load static %}

    {% block content %}
    <!-- Project -->
    <div class="in">
        <a class="animsition-link" href=".." data-animsition-out-class="overlay-slide-out-left" class="previous"><i class="fas fa-arrow-left"></i> Retour</a>
        <div id="project_header">
            <h1>{{ project.name }}</h1>
            <i>{{ project.date|date:"DATE_FORMAT" }}</i>
            <p><i><i class="fas fa-tags"></i><b> Langages :</b> {{ project.labels }}</i></p>
        </div>
        
        <p>{{ project.desc|safe }}</p>

        <ul id="gallery">
            {% for fichier in fichiers %}
                <a rel="zoom" href="{{ fichier.link.url }}" alt="{{ fichier.name }}"><img src="{{ fichier.link.url }}" style="width:400px;height:250px;" ></a>
            {% endfor %}
        </ul>

        <!-- Lightbox -->
        <div class="lightbox"></div>

        {% if project.github %}<a class="projectButtons" href="{{ project.github }}">Github URL <i class="fab fa-github fa-2x" style="float:right;"></i></a>{%  endif %}
        {% if project.demo %}<a class="projectButtons" href="{{ project.demo }}">Demo URL <i class="fas fa-eye fa-2x" style="float:right;"></i></a>{%  endif %}
    </div>
    {% endblock %}